# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Nodejs.gitlab-ci.yml

# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:16-alpine

stages:
  - build
  - lint
  - test

build_frontend:
  stage: build
  script:
    - cd ./frontend
    - npm install

lint_frontend:
  stage: lint
  script:
    - cd ./frontend
    - npm install
    - npm run format
    - npm run lint
  dependencies:
    - build_frontend
  allow_failure: false

test_frontend:
  stage: test
  script:
    - cd ./frontend
    - npm install
    - npm run test:unit
  dependencies:
    - build_frontend
  allow_failure: false

build_backend:
  stage: build
  script:
    - cd ./backend
    - apk update
    - apk add py-pip
    - apk add --no-cache python3-dev 
    - pip install --upgrade pip
    - pip --no-cache-dir install -r requirements.txt
  allow_failure: false

lint_backend:
  stage: lint
  script:
    - cd ./backend
    - apk update
    - apk add py-pip
    - apk add --no-cache python3-dev
    - pip install --upgrade pip
    - pip --no-cache-dir install -r requirements.txt
    - cd ..
    - pylint --rcfile backend/.pylintrc backend/
  dependencies:
    - build_backend
  allow_failure: false

test_backend:
  stage: test
  variables:
    MONGO_USERNAME: "root"
    MONGO_PASSWORD: "example"
    MONGO_HOSTNAME: "host.docker.internal"
    MONGO_PORT: "27017"
    BEARER_TOKEN: "AAAAAAAAAAAAAAAAAAAAAFvZlQEAAAAAKJ2aLLYYPFSQyRsPgwSonDACeT0%3DwJjK63Eys0ixVHxTaYjTs9eBgOIOrDkOKytKcixt1m4WX3X4Yi"
  script:
    - cd ./backend
    - apk update
    - apk add py-pip
    - apk add --no-cache python3-dev 
    - pip install --upgrade pip
    - pip --no-cache-dir install -r requirements.txt
    - python -m pytest src/test/
  dependencies:
    - build_backend
  allow_failure: false
