# The Deployment spec is very much similar to the one we created in the frontend deployment
# except that we are using a different image.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphex-staging-backend # TODO: Change the name to your application name with a backend suffix
  namespace: graphex-staging # TODO: Change the namespace to your application name with a staging suffix

spec:
  replicas: 1
  selector:
    matchLabels:
      # TODO: Change the app label to your application name with a backend suffix
      # Must match the app label in the template field.
      app: graphex-backend
  template:
    metadata:
      labels:
        # TODO: Change the app label to your application name with a backend suffix
        # Must match the app label in the selector field above.
        app: graphex-backend
    spec:
      containers:
        - name: graphex # TODO: replace this with your application name
          resources: {}
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: graphex-secrets
                  key: mongo-initdb-root-username

            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: graphex-secrets
                  key: mongo-initdb-root-password

            - name: MONGO_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: graphex-staging-configmap
                  key: mongo-host-for-backend

            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: graphex-staging-configmap
                  key: mongo-port-for-backend

            - name: MONGO_DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: graphex-staging-configmap
                  key: mongo-initdb-database

            - name: BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: graphex-secrets
                  key: bearer-token

            - name: REDDIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: graphex-secrets
                  key: reddit-username

            - name: REDDIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: graphex-secrets
                  key: reddit-password

            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: graphex-secrets
                  key: reddit-client-id

            - name: SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: graphex-secrets
                  key: reddit-secret-token

            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: graphex-secrets
                  key: openai-api-key

          ports:
            - containerPort: 8080
          image: registry.socs.uoguelph.ca/3760w23/t1/graphex/ubi/backend:latest
          imagePullPolicy: Always # Comment out this line if you are running locally

          # image: graphex-be:latest # TODO: replace this with your local image name to run locally or comment it out to run from the registry
          # imagePullPolicy: Never # Comment out the imagePullPolicy field if you are NOT running locally. Otherwise, set it to Never.

      imagePullSecrets:
        - name: regcred # TODO: replace this with your image pull secret name

